############# French navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
weight = 3
name = "2026 Events"
hasChildren = true

  [[main]]
  parent = "2026 Events"
  name = "St-Lawrence 2-day"
  url = "raid_stlaurent_2026/"
  weight = 1

  [[main]]
  parent = "2026 Events"
  name = "St-Lawrence (7h)"
  url = "raid_stlaurent7h_2026/"
  weight = 2

  [[main]]
  parent = "2026 Events"
  name = "St-Lawrence 2-day"
  url = "raid_stlaurent_2026/"
  weight = 3


[[main]]
weight = 4
name = "Past events"
hasChildren = true

  [[main]]
  parent = "Past events"
  name = "St-Lawrence 2-day"
  url = "raid_stlaurent_2025/"
  weight = 1

  [[main]]
  parent = "Past events"
  name = "St-Lawrence (5h)- 2025"
  url = "raid_stlaurent5h_2025/"
  weight = 2

  [[main]]
  parent = "Past events"
  name = "St-Lawrence (8h)- 2025"
  url = "raid_stlaurent8h_2025/"
  weight = 3

  [[main]]
  parent = "Past events"
  name = "Two-day - 2024"
  url = "jackalope_2024/"
  weight = 4

  [[main]]
  parent = "Past events"
  name = "6h - 2024"
  url = "jackalope6h_2024/"
  weight = 5

  [[main]]
  parent = "Past events"
  name = "4h - 2024"
  url = "jackalope4h_2024/"
  weight = 6

  [[main]]
  parent = "Past events"
  name = "Two-day - 2023 "
  url = "jackalope_2023/"
  weight = 7

  [[main]]
  parent = "Past events"
  name = "6h - 2023"
  url = "jackalope6h_2023/"
  weight = 8

  [[main]]
  parent = "Past events"
  name = "4h - 2022"
  url = "jackalope_short/"
  weight = 9

  [[main]]
  parent = "Past events"
  name = "12h - 2022"
  url = "jackalope_long/"
  weight = 10

[[main]]
name = "Partners"
url = "partenaires/"
weight = 5

[[main]]
name = "Race reports"
url = "blog/"
weight = 6

[[main]]
name = "FAQ"
url = "faq/"
weight = 7

[[main]]
name = "Contact"
url = "contact/"
weight = 8


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "St-Lawrence AR"
url = "raid_stlaurent_2026/"
weight = 2

[[footer]]
name = "St-Lawrence AR 7h"
url = "raid_stlaurent7h_2026/"
weight = 3

[[footer]]
name = "FAQ"
url = "faq/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 5
